steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nwsl-frontend:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nwsl-frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nwsl-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nwsl-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=$$OPENAI_API_KEY'
    secretEnv: ['OPENAI_API_KEY']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/nwsl-frontend:$COMMIT_SHA'

# Use cloud logging only to avoid logs bucket requirement
options:
  logging: CLOUD_LOGGING_ONLY

# Configure the build to access secret environment variables
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
      env: 'OPENAI_API_KEY'