name: Sync Documentation from nwsl_data

on:
  repository_dispatch:
    types: [docs-updated]
  workflow_dispatch:
  
jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout nwsl_data_platform
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout nwsl_data (source)
      uses: actions/checkout@v4
      with:
        repository: tom-mcmillan/nwsl_data
        path: nwsl_data_source
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install MkDocs dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Sync documentation content
      run: |
        echo "🔄 Syncing documentation from nwsl_data..."
        rm -rf docs/
        cp -r nwsl_data_source/docs/ docs/
        
    - name: Build documentation
      run: |
        echo "🔨 Building documentation with MkDocs Material..."
        mkdocs build
        
    - name: Commit updated documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ public/docs/
        if git diff --staged --quiet; then
          echo "No documentation changes to commit"
        else
          git commit -m "📖 Auto-sync documentation from nwsl_data

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        fi